### ISSUE TITLE
Getting min and max coordinates of the thumb while scrolling

### ISSUE THREAD

**Issue by EvaniRam** [lukelorusso/VerticalSeekBar#10]
Hi Luke,
   I just  wanted to know is there any possibility of getting minimum and maximum progress values of the thumb (or Range )while moving on  the bar ?
I have a situation where I need to send the coordinates of the thumb's minimum and maximum values to api 

![image](https://user-images.githubusercontent.com/6368710/79844438-49f29d00-83d9-11ea-8027-9620ef6bb0fa.png)

**Comment by lukelorusso** [comment]
Hi EvaniRam,

thank you for your interest.
I imagine that if you know your thumb's height, you can say that for each progress value:

`val max = progressValue + (thumbHeight / 2)`
and
`val min = progressValue - (thumbHeight / 2)`

then you can listen to:

```
mainVerticalSeekBar.setOnProgressChangeListener { progressValue ->
    // do your stuff
}
```
