### ISSUE TITLE
Is there a similar function just like onStopTrackingTouch of SeekBar with verticalSeekBar control in Android Studio?

### ISSUE THREAD

**Issue by mycwcgr** [lukelorusso/VerticalSeekBar#2]
Is there a similar function just like onStopTrackingTouch of SeekBar with verticalSeekBar control in Android Studio?

Would you please see the question at https://stackoverflow.com/questions/58316444/is-there-a-similar-function-just-like-onstoptrackingtouch-of-seekbar-with-vertic

**Comment by lukelorusso** [comment]
Hi mycwcgr,

in version 1.2.2 (soon available) take a look at "Listeners" in the README file ;)

Thank you for your interest!
