### ISSUE TITLE
Problem:  VerticalSeekBar that's not really integrate in constraint layout. 

### ISSUE THREAD

**Issue by mycwcgr** [lukelorusso/VerticalSeekBar#3]
Would you please see the question at https://stackoverflow.com/questions/58279019/how-can-i-set-hight-of-vertical-control-in-constraintlayout-in-android-studio

**Comment by lukelorusso** [comment]
Hi mycwcgr,

I just tested the answers given to you and actually both are working fine: you can:
1) incapsulate the VSB in a LinearLayout, giving `android:layout_height="match_parent"` to the VSB

[Answer 1](https://stackoverflow.com/a/58283283/9181419)

2) set `android:layout_height="0dp"` to the VSB and constrain it as you like:
```
<com.lukelorusso.verticalseekbar.VerticalSeekBar
        android:id="@+id/verticalSeekBar"
        android:layout_width="10dp"
        android:layout_height="0dp"
        ...
        app:layout_constraintBottom_toTopOf="@+id/btnAction"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintTop_toBottomOf="@+id/btnMenu"
```

[Answer 2](https://stackoverflow.com/a/58281671/9181419)

Thank you!
