### ISSUE TITLE
set maxValue from attribute list

### ISSUE THREAD

**Issue by ModischFabrications** [lukelorusso/VerticalSeekBar#5]
Setting the vsb_progress from the attributes while setting a new maxValue from code seems counterintuitive to me, did I miss something?

It looks like setting up the max (and min) progress from the attribute list is currently not supported.

**Comment by ModischFabrications** [comment]
In my case I am trying to use a "discrete" slider with values from 1 to 3, which needs manual tweaking.

**Comment by lukelorusso** [comment]
Hi ModischFabrications,

you're absolutely right: there’s no reason why maxValue should not be set from attributes!

Look for v.1.2.3 (releasing soon!) and thank you 🙏
