### ISSUE TITLE
allow Listener class

### ISSUE THREAD

**Issue by ModischFabrications** [lukelorusso/VerticalSeekBar#6]
I miss the ability to register a class to be able to allocate ressources and more for my listener. 

Is it possible to define an interface and implement registering with it? 

https://github.com/harjot-oberai/Croller is doing something similar and might be a nice reference.

**Comment by ModischFabrications** [comment]
Again, in my case I want to implement button sounds by intercepting changes.

**Comment by ModischFabrications** [comment]
Using the exposed onTouch events inherited from FrameLayout won't work either.

**Comment by ModischFabrications** [comment]
Fixed in my fork: https://github.com/ModischFabrications/VerticalSeekBar

I could make a pull request if this library is still maintained, but I would need to look into it first.

**Comment by lukelorusso** [comment]
Hi ModischFabrications,

great idea! I'll take inspiration from your fork and integrate the listener 👍

Thank you for your support!
