### ISSUE TITLE
Width/height setting is fixed in constructor, not in `onMeasure()`

### ISSUE THREAD

**Issue by pfoof** [lukelorusso/VerticalSeekBar#7]
The view renders properly as long as height can be determined with fixed number of `dp` or `match_parent`.
However, in case of `wrap_content` with `layout_weight` in `LinearLayout` as parent, the height becomes 0 (checked, debugged). Thus I suggest setting it again by overriding `onMeasure`.
**Use case:** when we want to have two `VerticalSeekBar`s with equal height filling the parent view.

Currently it's not on my priority, but if I find time I might post a fix.

**Comment by lukelorusso** [comment]
Hi pfoof,

I highly encourage you to open a pull request! Try to focus just on this issue and I'll review it :)
Thank you so much.

**Comment by ComradeVanti** [comment]
Any news on this?

**Comment by lukelorusso** [comment]
@KingVanti https://github.com/lukelorusso/VerticalSeekBar/issues/13
